apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: braynsviewer-dev
    namespace: bbp-ou-visualization
spec:
    secretName: braynsviewer-dev-certificate
    issuerRef:
        name: bbp-acme-issuer
    dnsNames:
        - braynsviewer.kcp.bbp.epfl.ch
