apiVersion: apps/v1
kind: Deployment
metadata:
    name: braynsviewer-dev
    namespace: bbp-ou-visualization
    labels:
        app: braynsviewer-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: braynsviewer-dev
    template:
        metadata:
            labels:
                app: braynsviewer-dev
        spec:
            terminationGracePeriodSeconds: 30
            containers:
                - name: braynsviewer-dev
                  image: bbpgitlab.epfl.ch:5050/viz/brayns/braynsviewer:latest
                  imagePullPolicy: "Always"
                  ports:
                      - containerPort: 8443
                  volumeMounts:
                      - name: braynsviewer-dev-nginx
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: default.conf
                        readOnly: true
                      - name: braynsviewer-dev-certificate
                        mountPath: /etc/tls
                        readOnly: true
            imagePullSecrets:
                - name: viz-pull-registry-credentials
            volumes:
                - name: braynsviewer-dev-nginx
                  configMap:
                      name: braynsviewer-dev
                      items:
                          - key: nginx-default.conf
                            path: default.conf
                - name: braynsviewer-dev-certificate
                  secret:
                      defaultMode: 420
                      secretName: braynsviewer-dev-certificate
