apiVersion: v1
kind: Service
metadata:
    name: braynsviewer-dev
    namespace: bbp-ou-visualization
spec:
    selector:
        app: braynsviewer-dev
    ports:
        - protocol: TCP
          port: 443
          targetPort: 8443
